[project]
name = "tfg-ocean-debris-qg"
version = "4.6"
description = "Simulación QG barotrópica oceánica para dispersión de partículas (TFG)"
requires-python = ">=3.9"
dependencies = [
    "numpy",
    "cupy-cuda12x",
    "scipy",
    "matplotlib",
    "tqdm",
    "numba",
    "netCDF4",
]

[tool.uv]
package = false
